### ISSUE TITLE
Rockstar Games Launcher doesn't work correctly

### ISSUE THREAD

**Issue by Jepl4r** [italomandara/CXPatcher#87] opened 2023-07-27 18:30 UTC
I installed the Rockstar Games Launcher inside CrossOver and then I downloaded GTA 5.
When I play the game I can't change the resolution nor the display mode (I can only select Windowed or Borderless Windowed).
This is without DXVK enabled.
If I enable it, the Launcher either remains stuck on loading or it loads in offline mode and I can't start the game cause it crashes.

I'm using GPTK 1.0.2 and CrossOver 22.1.1 patched with CXPatcher 0.2.18

**Comment by Jepl4r** [comment] 2023-07-27 18:43
Here's the cxlog (DXVK is enabled)
[Rockstar Games Launcher.cxlog.zip](https://github.com/italomandara/CXPatcher/files/12186838/Rockstar.Games.Launcher.cxlog.zip)

**Comment by Gcenx** [comment] 2023-07-27 20:17
> I installed the Rockstar Games Launcher inside CrossOver and then I downloaded GTA 5. When I play the game I can't change the resolution nor the display mode (I can only select Windowed or Borderless Windowed). This is without DXVK enabled.

it seems that’s just something that Apple is currently forcing with D3DMetal

> If I enable it, the Launcher either remains stuck on loading or it loads in offline mode and I can't start the game cause it crashes.

The first issue seems inconsistent.

There’s no way DXVK dlls are forcing the rockstar launcher into offline mode.

> I'm using GPTK 1.0.2 and CrossOver 22.1.1 patched with CXPatcher 0.2.18

Could you grab a second copy of CrossOver-22.1.1 and apply CXPatcher again but skip “external resources”.

Now launch this new copy, select your GTA bottle and launch “winecfg”, click the “libraries” tab, find “dxgi” in the list and remove it, now click “apply” and exit winecfg.

Toggle DXVK off & on again then try running Rockstar Launcher again. This will give a better idea of what’s really happening but I have a feeling DXVK dxgi is just causing UE headaches again.

<br>

Due to the ugly way Apple implemented D3DMetal it replaces wines building dlls with there own stub dlls, so we’d tried forcing DXVK dxgi when avalible but that seems to have caused other regressions.

**Comment by Jepl4r** [comment] 2023-07-27 20:36
I'll try that later cause I deleted the bottle and I have to redownload GTA 5. I will let you know if it works.

**Comment by Jepl4r** [comment] 2023-07-28 19:43
@Gcenx I tried to do what you said (minus removing the dxgi.dll as it was not there cause I recreated the bottle with CrossOver patched without GPTK) and now the Rockstar Games Launcher crashes as soon as I start it.

Here's the log
[Rockstar Games Launcher.cxlog.zip](https://github.com/italomandara/CXPatcher/files/12197812/Rockstar.Games.Launcher.cxlog.zip)

**Comment by Gcenx** [comment] 2023-07-28 19:48
I’ll need to take a look over the weekend.

Just want to make sure that you installed Rockstar Games Launcher via CrossOver menu? (Aka installed via there crosstie)

**Comment by Jepl4r** [comment] 2023-07-28 19:50
Yep, I used the crosstie

**Comment by Jepl4r** [comment] 2023-07-30 15:02
@Gcenx I used CrossOver with CXPatcher 0.2.17 and GPTK 1.0.2 and I got it to work. Now the only problem is that GTA 5 doesn't save the DX version, it always revert back to DX10 even if I change it from the settings.xml file or I use the -dx11 argument in the Launcher.
I tried it by not including GPTK too, but it has the same problem as CrossOver with CXPatcher 0.2.18

**Comment by Gcenx** [comment] 2023-07-30 16:07
I’ll see if I have time later today after I’ve caught up on the Winehq macOS packages as I’m behind.

GTAV only really supports DirectX11 but can run using DirectX11 feature level 10 that’s what you’re really getting.

For each test did you use a newly generated bottle using the newly patched copy of CrossOver?, using existing bottles won’t be viable.

I own GTAV on Steam so it’ll easy for me to trash the bottles between tests.

**Comment by Gcenx** [comment] 2023-07-30 16:08
> I tried it by not including GPTK too, but it has the same problem as CrossOver with CXPatcher 0.2.18

This one seems the most odd to me.

**Comment by Jepl4r** [comment] 2023-07-30 16:15
> GTAV only really supports DirectX11 but can run using DirectX11 feature level 10 that’s what you’re really getting.

I know that. What I'm saying is that it doesn't seem to save the DirectX version when you change it from the settings. It only uses DirectX10, even DirectX10.1 doesn't work.

> For each test did you use a newly generated bottle using the newly patched copy of CrossOver?, using existing bottles won’t be viable.

Yeah, I used a new bottle for every test.

**Comment by Jepl4r** [comment] 2023-07-30 16:18
> > I tried it by not including GPTK too, but it has the same problem as CrossOver with CXPatcher 0.2.18
> 
> This one seems the most odd to me.

I don't know. If I try to start GTA 5 from the shortcut, this is what I get. ( I even reinstalled it to be sure)
<img width="382" alt="Screenshot 2023-07-30 alle 18 17 01" src="https://github.com/italomandara/CXPatcher/assets/115885800/64729710-d2f5-4090-8336-6b30512050b4">

And if I try to open the Launcher, this is what I get.
<img width="429" alt="Screenshot 2023-07-30 alle 18 17 32" src="https://github.com/italomandara/CXPatcher/assets/115885800/d80748b8-a8ff-425d-b43c-06d5b61d73f0">

**Comment by Gcenx** [comment] 2023-07-30 17:26
@Jepl4r confirmed your issue and think I’ve found the issue.

**Comment by Jepl4r** [comment] 2023-07-30 18:56
Great, I'll wait for the fix.

**Comment by Gcenx** [comment] 2023-07-30 20:48
@Jepl4r you can grab a fixed copy here [CXPatcher-hotfix.app.zip](https://github.com/italomandara/CXPatcher/releases/download/V0.2.18/CXPatcher-hotfix.app.zip)

Unfortunately it will require a new Bottle _again_, not sure if you're able to move GTAV game files over or not since I own the game on Steam Rockstar Games Launcher is only used to launch the game.

I'd setup a clean Steam bottle then installed Rockstar Games Launcher via GTAV, Rockstar Games Launcher installed and run without issue and GTAV ran.

**Comment by Gcenx** [comment] 2023-07-30 22:26
@Jepl4r actually just grab the latest release over the “hotfix” build I’d thrown up before.

**Comment by Jepl4r** [comment] 2023-07-30 23:41
> Unfortunately it will require a new Bottle _again_, not sure if you're able to move GTAV game files over or not since I own the game on Steam Rockstar Games Launcher is only used to launch the game.

No problem. I can move the GTA 5 folder inside the new bottle and start a scan to search for games from the Rockstar Launcher.
Thanks for the fix 😄

**Comment by Jepl4r** [comment] 2023-07-31 00:29
@Gcenx I tried patching a clean version of CrossOver with CXPatcher 0.2.19 and GPTK, but unfortunately it has the same behaviour as CXPatcher 0.2.18

The Launcher and GTA 5 only works if you don't include GPTK. With DXVK the performance are worst (I get half the fps) and all the cars have green windows.
<img width="1512" alt="Screenshot 2023-07-31 alle 02 20 27" src="https://github.com/italomandara/CXPatcher/assets/115885800/46963704-689a-40ac-8d1b-949d45c09d94">

So far I had more luck using CrossOver with GPTK and CXPatcher 0.2.17

**Comment by Gcenx** [comment] 2023-07-31 01:24
@Jepl4r think I've found the remaining issue and figured out why it was working on my system

**Comment by Gcenx** [comment] 2023-07-31 02:04
@Jepl4r the current issues should have been fully resolved by V0.2.20 release, I can load Rockstar Games Launcher now with D3DMetal.

**Comment by Jepl4r** [comment] 2023-07-31 02:08
@Gcenx Alright, I'll test it and report back.

**Comment by Jepl4r** [comment] 2023-07-31 02:37
@Gcenx Now it works again. The issue that GTA 5 doesn't save the DirectX version when you change it to 10.1 or 11 while using GPTK is still there, but I can leave with that.
Thanks again for the help.

**Comment by Gcenx** [comment] 2023-07-31 02:58
> Now it works again.

Glad that's gotten everything working for you again.

> The issue that GTA 5 doesn't save the DirectX version when you change it to 10.1 or 11 while using GPTK is still there.

That ones something we can't really do anything for since that's D3DMetal, Apple may continue to expand there DirectX11 support in later revisions.

**Closed by Gcenx** 2023-07-31 02:58 UTC
