### ISSUE TITLE
Crossover 23 released

### ISSUE THREAD

**Issue by sebolio** [italomandara/CXPatcher#110] opened 2023-08-27 00:17 UTC
Are there any plans to support it? Or does it not need this patch anymore?

**Comment by endomorphine** [comment] 2023-08-27 17:50
read existing issues before creating new ones https://github.com/italomandara/CXPatcher/issues/101#issuecomment-1693095769

**Comment by italomandara** [comment] 2023-08-27 23:33
duplicate of #101

**Closed by italomandara** 2023-08-27 23:33 UTC
