### ISSUE TITLE
CO patched with v.0.3.3 doesn't show window.

### ISSUE THREAD

**Issue by serista** [italomandara/CXPatcher#129] opened 2023-09-28 11:51 UTC
Sonoma 14.0, CO 22.1.1, CXP 0.3.3.  After patching (with D3DMetal option enabled and separate path disabled) CrossOver starts without errors, there is CO title bar, but its window nowhere to be seen.

**Comment by italomandara** [comment] 2023-09-28 12:06
Can you please give me more details so that i can replicate? It works just fine for me, for example: was the crossover app already patched with an older cxpatcher? what are the steps to reproduce the issue?

**Comment by serista** [comment] 2023-09-28 12:16
It was patched before many times with older versions of CXP, but I unpatch it every time before I use newer version. It's M1, public release of Sonoma, CO 22.1.1 as I mentioned before. I did a usual procedure (unpatched the CO) and patched with CXP. Tried it several times - same result. There is only menu bar but no window and no any error messages. 

Same with 0.3.2

0.3.1 works.

**Comment by italomandara** [comment] 2023-09-28 14:45
ok so that means re-patching was broken since the folder re-arrangement, good to know.
meanwhile can you try on a fresh copy of crossover 22.1.1 please?

**Comment by serista** [comment] 2023-09-28 19:35
I'll try it tomorrow if it's still needed.

**Comment by serista** [comment] 2023-09-29 11:51
I reinstalled CO and it's still the same with 0.3.3 and 0.3.2  - no window. Moreover, somehow I could not unpatch CO after patching (there was error about "either it's not patched or patched with incompatible version") until I repatched it with "allow repatch" enabled, after that it could be unpatched. I'm on 0.3.1 now.

**Comment by italomandara** [comment] 2023-09-29 11:56
> I reinstalled CO and it's still the same with 0.3.3 and 0.3.2 - no window. Moreover, somehow I could not unpatch CO after patching (there was error about "either it's not patched or patched with incompatible version") until I repatched it with "allow repatch" enabled, after that it could be unpatched. I'm on 0.3.1 now.

so if you patched a pristine, fresh downloaded crossover app with 0.3.3 without previously patching it with some older version. this is something else.

**Comment by serista** [comment] 2023-09-29 12:08
> so if you patched a pristine, fresh downloaded crossover app with 0.3.3 without previously patching it with some older version. this is something else.

Yes, I deleted CO, then installed it from scratch, checked that it run fine, quit it, patched it with 0.3.3 without D3DMetal this time, and got no window after that.

**Comment by serista** [comment] 2023-09-30 14:55
OK, it works now. I repatched the fresh copy again after I removed installed.

**Comment by italomandara** [comment] 2023-09-30 15:07
This is probably because i re-uploaded another build with a new code signature. Maybe that was causing issues

**Comment by serista** [comment] 2023-09-30 15:15
> This is probably because i re-uploaded another build with a new code signature. Maybe that was causing issues

You should also re-upload older versions, they also cause "will damage your computer" message.

**Comment by italomandara** [comment] 2023-09-30 15:41
> > This is probably because i re-uploaded another build with a new code signature. Maybe that was causing issues
> 
> You should also re-upload older versions, they also cause "will damage your computer" message. I tried 0.3.1 f.e.

Thanks for reporting that!

**Comment by serista** [comment] 2023-09-30 18:40
> Thanks for reporting that! I will re-upload all of them or maybe just remove the artifacts from old versions

My pleasure. Unrelated, by I wanted to ask if it's possible to do something with D3DMetal messing with DXVK? I mean that if D3DMetal is integrated then my games that had worked fine via DXVK cease to work. Stray as example.

**Comment by serista** [comment] 2023-09-30 19:15
I don't know what's going on but CO (+1.3.3) once again doesn't open window. It worked consistently for few hours I many times repatched and unpatched it alterating beetwin D3DMetal and no D3DMeta and it worked fine. Now after few hours (and some computer restarts) I run it again and here we go - no window once again ( Something very strange is going on, all else working fine including Whisky.

**Comment by italomandara** [comment] 2023-09-30 19:56
![Screenshot 2023-09-30 at 20 55 32](https://github.com/italomandara/CXPatcher/assets/12135454/9ce1f62a-aad8-41ef-816c-10008e8bf985)
For the avoidance of doubt, is this the window you aren't able to see?

**Comment by serista** [comment] 2023-09-30 20:00
> For the avoidance of doubt, is this the window you aren't able to see?

Yes ) After unpatching with 0.3.3 and patching again it works again. Bizzare. It's kind of random, but when it doesn't work it doesn't work. I tried to run it 10 or 20 times in a row until I repatched. It started to work again right after I unpatched it.

**Comment by italomandara** [comment] 2023-09-30 20:02
CXPatcher just changes some libs, the ui in crossover is a separate entity that CXPatcher doen't mess with, so it could be some other problem, do you manually change something in crossover for example? Is your license valid? can't think of anything I can fix on my end.

**Comment by serista** [comment] 2023-09-30 20:06
> do you manually change something in crossover for example? Is your license valid? can't think of anything I can fix on my end.

I did some manipulations with bottles. Removed and added some and also moved games from and to virtual C drives in the bottles. I also enabled and disabled DXVK switch. I'll try not change anything and see how it works.

**Comment by serista** [comment] 2023-09-30 20:43
> CXPatcher just changes some libs, the ui in crossover is a separate entity that CXPatcher doen't mess with

The thing is that if CO doesn't work, once I unpatch it with CXP, it starts to work right away, so I think CXP must be related somehow. Not sure of course. What is really strange that it still works if I patch it again.

**Comment by serista** [comment] 2023-10-01 08:40
After booting computer today the first thing I tried was launching CO, but it once again didn't show window. Then I run a game that uses it directly from a file manager. After that it started to work properly again. Hmm.

**Comment by italomandara** [comment] 2023-10-01 11:52
> After booting computer today the first thing I tried was launching CO, but it once again didn't show window. Then I run a game that uses it directly from a file manager. After that it started to work properly again. Hmm.

I'm not able to replicate your issue, 
If crossover is in your main Applications folder and it hasn't been renamed, try to run this on your terminal `/Applications/CrossOver.app/Contents/MacOS/CrossOver` and paste all you get in the terminal logs please.

**Comment by serista** [comment] 2023-10-07 11:13
I'm sorry, I need to reinstall my staff before that, CX is uninstalled and I'm using Whisky for now. BUT CX+CXP 0.3.3 was working fine and consistently for a few days since that problem occurred multiple times in the beginning and I couldn't repeat the problem anymore, maybe it was some problem with  installation in my particular case (my bottle folder is on the external drive btw), especially if nobody else has had that issue as it seems.

**Comment by italomandara** [comment] 2023-10-07 13:11
I'll close this then. Please feel free to re-open it in the future if the issue persists or you find other people having the same issue

**Closed by italomandara** 2023-10-07 13:11 UTC
Labels: bug
