### ISSUE TITLE
CS2 getting stuck

### ISSUE THREAD

**Issue by agent-carl** [italomandara/CXPatcher#154] opened 2023-11-16 21:03 UTC
> I have a problem with cs2 getting stuck after 7-10 minutes of gameplay.
> the game just stops and doesn't react to anything.

> I used the crossover with the patch from CXpatcher, then tried the clean version of the crossover but the problem remained

> CXpatcher 4.7
> Crossover 23.6

**Comment by italomandara** [comment] 2023-11-17 09:08
closing this issue as a duplicate of https://github.com/italomandara/CXPatcher/issues/148

**Closed by italomandara** 2023-11-17 09:08 UTC
